### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by mttdffy** [peek/peek-mongo#5]
Theres been updates to this gem to update compatibility, that I need. Is a release being cut anytime soon?

**Comment by dewski** [comment]
I don't have an active Mongo project anymore to properly test this. Could you point `peek-mongo` to the git HEAD and confirm it works in your project?

```ruby
gem 'peek-mongo', github: 'peek/peek-mongo'
```

**Comment by mttdffy** [comment]
it works. We've been pointing at master while in development.

**Comment by skreem** [comment]
@dewski It is still working in my project as well (where I refactored the updates to master from).

**Comment by dewski** [comment]
Released [1.2.0](https://rubygems.org/gems/peek-mongo/versions/1.2.0)! Thank you for your patience everyone.
